imu:
    topic_name: /sim/sensor/imu
    gravity:
        x:  0.0
        y:  0.0
        z: -9.7942
    bias:
        angular_velocity:
            x: 0.0
            y: 0.0
            z: 0.0
        linear_acceleration:
            x: 0.0
            y: 0.0
            z: 0.0
            
pose:
    frame_id: NED
    topic_name: 
        #ground_truth: /pose/ground_truth  #TODO
        ground_truth: /sim/sensor/gps
        estimation: /pose/estimation  
 