# motion def:
motion_file: allan_variance_analysis.csv
# IMU params:
imu: 1
# sample frequency of simulated GNSS/IMU data:
sample_frequency:
    imu: 100.0
    gps: 100.0
# topic name:
topic_name: /sim/sensor/imu
gps_topic_name: /sim/sensor/gps
# output rosbag path:
output_path: /home/chahe/project/sensor-fusion-for-localization-and-mapping/workspace/data/allan_variance_analysis
# output name:
output_name: stable_speed.bag